---
- name: create databases
  mysql_db:
    name: "{{ item.key }}"
    encoding: "{{ item.value.encoding | default(omit) }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_host: "{{ mysql_host }}"
    login_port: "{{ mysql_port }}"
  loop: "{{ content.dbs|default({})|dict2items }}"

- name: create users
  mysql_user:
    name: "{{ item.key }}"
    host: '%'
    priv: "{{ item.value.privs|join('/') if item.value.privs|default(False) else omit }}"
    password: "{{ item.value.pass|default(omit) }}"
    update_password: "{{ 'always' if item.value.pass|default(False) else 'on_create' }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_host: "{{ mysql_host }}"
    login_port: "{{ mysql_port }}"
  loop: "{{ content.users|default({})|dict2items }}"
